
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           39312
     no. of nonzeroes in lower triangle of a =          932861
     no. of nonzeroes in the factor l        =        15029428
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            1388
     maximum order of a front matrix         =            1053
     maximum size of a front matrix          =          554931
     maximum size of a front trapezoid       =          554931
     METIS reordering method used 
     no. of floating point ops for factor    =      7.4131D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =               0
     number of negative pivots               =               1
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               2
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.002000
     time (cpu & wall) for ordering          =        1.750000        1.585000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.281250        0.134000
     time (cpu & wall) for numeric factor    =        0.953125        0.509000
     computational rate (gflops) for factor  =        7.777721       14.564126
     time (cpu & wall) for numeric solve     =        0.062500        0.021000
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     no input or output performed

  Total Solver Memory allocated              =      176.055 MB
