
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           39312
     no. of nonzeroes in lower triangle of a =          932861
     no. of nonzeroes in the factor l        =        15034980
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            1388
     maximum order of a front matrix         =            1053
     maximum size of a front matrix          =          554931
     maximum size of a front trapezoid       =          554931
     METIS reordering method used 
     no. of floating point ops for factor    =      7.4131D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =               0
     number of negative pivots               =               1
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.9269-322
     number of 1x1 pivots                    =           39312
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               0
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               2
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.031250
     time (cpu & wall) for ordering          =        0.000000        0.828125
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.062500
     time (cpu & wall) for numeric factor    =        0.000000        0.437500
     computational rate (gflops) for factor  =        Infinity       16.944321

     no input or output performed

  Total Solver Memory allocated              =        0.000 MB
